export const labels = {
  en: {
    title: 'StreamVitals',
    subtitle: 'OneAquaHealth IEEE Global Hackathon 2026',
    takeVitals: 'Take the stream\'s vitals',
    answerQuestions: 'Answer Questions',
    describeWhatYouSee: 'Describe What You See',
    aiMayInterpret: 'AI may interpret input. AI may not adjudicate.',
    tier1: 'No Priority Concern Detected',
    tier2: 'Needs Attention',
    tier3: 'Further Assessment Recommended',
    sufficient: 'Sufficient',
    partial: 'Partial',
    insufficient: 'Insufficient',
    confirm: 'Confirm',
    proceed: 'Proceed',
    retake: 'Retake Assessment',
    howItWorks: 'How It Works',
    referenceContext: 'Reference Context',
    ruleInspector: 'Rule Inspector',
    notADiagnosis: 'This is not a diagnosis.',
    notCertified: 'FHIR R4 export — draft implementation guide, not certified.',
    next: 'Next',
    skipAI: 'Skip AI',
    enableAI: 'Enable AI to extract observations from your text',
    highConfidence: 'High confidence',
    uncertain: 'Uncertain',
    answerTheQuestion: 'Answer the question',
    selectAllStates: 'Select a state for each indicator',
    reviewConfirm: 'Review and confirm all answers before proceeding',
  },
  pt: {
    title: 'StreamVitais',
    subtitle: 'OneAquaHealth IEEE Global Hackathon 2026',
    takeVitals: 'Tome as vitalidades do riacho',
    answerQuestions: 'Responder Perguntas',
    describeWhatYouSee: 'Descrever o que vê',
    aiMayInterpret: 'A IA pode interpretar a entrada. A IA não pode adjudicar.',
    tier1: 'Sem Preocupação de Prioridade Detectada',
    tier2: 'Precisa de Atenção',
    tier3: 'Avaliação Adicional Recomendada',
    sufficient: 'Suficiente',
    partial: 'Parcial',
    insufficient: 'Insuficiente',
    confirm: 'Confirmar',
    proceed: 'Prosseguir',
  },
} as const;

export type Language = keyof typeof labels;
